swagger: '2.0'
info:
  version: v1
  title: Invite Microservice
  description: Invite API
paths:
  "/api/Users":
    get:
      tags:
      - Users
      responses:
        '200':
          description: Success
          schema:
            uniqueItems: false
            type: array
            items:
              "$ref": "#/definitions/User"
        

    post:
      tags:
      - Users
      parameters:
      - name: value
        in: body
        required: false
        schema:
          $ref: '#definitions/UserEmail'
      responses:
        '200':
          description: Success
        '400':
          description: Bad Requests
  "/api/Users/verify":
    post:
      tags:
      - Users
      parameters:
      - name: value
        in: body
        required: false
        schema:
          type: string
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
definitions:
  User:
    type: object
    properties:
      id:
        format: int32
        type: integer
      email:
        type: string
      token:
        type: string
  UserEmail:
    type: object
    properties:
      email:
        type: string
        format: email